### ISSUE TITLE
Look into rate limits

### ISSUE THREAD

**Issue by zzak** [zzak/action-discord#5]
This build failed due to rate limits, is there something we need to do?
https://github.com/rails/rails/actions/runs/4570061339/jobs/8067008729

**Comment by dentarg** [comment]
Yes, I suspect this isn't working as intended

https://github.com/zzak/action-discord/blob/2edb53786004cf3d17fa27315d671f3dcbc2b269/main.rb#L22

I think the way to address it is to use add an input for users of the action to pass in a github token: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#example-1-passing-the-github_token-as-an-input

It also sounds like the action should be able to get the token from `github.token` even if not passed in explicitly, so I guess it could be read and passed on here

https://github.com/zzak/action-discord/blob/2edb53786004cf3d17fa27315d671f3dcbc2b269/action.yml#L25-L27

**Comment by zzak** [comment]
Yep, I had incorrectly assumed the default actions token was available in the environment, so we were making unauthenticated requests (which get rate limited much faster).
